Repository metwork-framework/docker-mfext-centos6-buildimage, pull requests merged in 2019-09, with the labels that each got.

#38 chore: add gperf (required to build fontconfig)
  Dockerfile
Labels: Status: Review Needed

#41 build: add x-devel libraries and reformat files to limit layers
  Dockerfile
Labels: Merge Now, Status: Review Needed

#42 build: add missing libpng-devel (previously installed as pango-devel …
  Dockerfile
Labels: Merge Now, Status: Review Needed

#44 Revert "build: add missing libpng-devel (previously installed as pang…
  Dockerfile
Labels: Merge Now

#45 build: add missing pixman-devel (previously installed as pango-devel …
  Dockerfile
Labels: Merge Now
