Repository metwork-framework/docker-mfext-centos6-buildimage, pull requests merged in 2020-12, with the labels that each got.

#61 feat: change centos6 base image because of centos6 EOL
  Dockerfile
Labels: backport-to-0.9, backport-to-1.0

#65 build: force a ci build
  README.md
Labels: Status: Merge Now

#66 build: Update Dockerfile
  Dockerfile
Labels: Status: Merge Now

#67 build: to force a ci build
  README.md
Labels: Status: Merge Now

#68 build: to force a CI build
  README.md
Labels: Status: Merge Now

#69 build: changes for centos6 EOL
  Dockerfile
Labels: Status: Merge Now, backport-to-0.9, backport-to-1.0

#77 build: release_0.9 is built with devtoolset-7
  Dockerfile
Labels: Status: Review Needed

#79 feat: add libuuid-devel which allows to build python with uuid support
  Dockerfile
Labels: Status: Review Needed

#81 build: remove cmake and cmake3 (as cmake is now built in layer core@m…
  Dockerfile
Labels: Status: Review Needed
